/*
 * Copyright (c) 2020, https://github.com/911992 All rights reserved.
 * License BSD 3-Clause (https://opensource.org/licenses/BSD-3-Clause)
 */

 /*
WAsys_pojo_http_data
File: Fillable_Object.java
Created on: May 13, 2020 1:17:53 AM
    @author https://github.com/911992
 
History:
    0.2 (20200605)
        • Updated/fixed documentation
        • Changed arg_success arg name to arg_result of method set_object_fill_result

    0.1.11(20200601)
        • Added part_streaming_done(:String,:int.:bool):void method

    0.1.3(20200521)
        • Updated the header(this comment) part
        • Added some javadoc
        • Set the default err message gen to false

    initial version: 0.1(20200510)
 */
package wasys.lib.pojo_http_data.api;

import java.io.InputStream;
import wasys.lib.pojo_http_data.Generic_Object_Filler;
import wasys.lib.pojo_http_data.api.annotations.No_Param;

/**
 * Defines a fillable POJO object.
 * <p>
 * Any POJO wish to be a fillable type should implement this interface(or its adapters).
 * </p>
 * <p>
 * It contains required methods to be implemented to track the correct state of a filled POJO by the filler module.
 * </p>
 * @author https://github.com/911992
 */
public interface Fillable_Object {

    /**
     * Specifies the type parsing mode.
     * <p>
     * This method is called <b>once</b>, <b>if and if</b> the implementer type has not annotated by {@link No_Param}, otherwise for each filling op, type will be parsed again.
     * </p>
     * <p>
     * If the parse mode is set to {@code Reflection_Type_Fields}, so it means the parser should find and parse the fields need to be fill at runtime(once) using reflection(type scraping)
     * </p>
     * <p>Else if it's {@code Type_Manipulator}, so the parser will call the {@code get_type_descriptor(void):Fillable_Object_Manipulator} that should return a nun null @{code Fillable_Object_Manipulator} instance that explains the type manually by user
     * </p>
     * <p>By default it return {@code Reflection_Type_Fields}</p>
     * @return type parsing mode
     */
    default public Object_Fill_Mode fill_mode() {
        return Object_Fill_Mode.Reflection_Type_Fields;
    }

    /**
     * Specifies the part(file upload) streaming mode for each stream-able({@code OutputStream}) field.
     * <p>
     * This method is called <b>after</b> method {@code prepare_for_part} is called to ask how does the part(which has triggered to {@code prepare_for_part} method) should be treated(streamed)
     * </p>
     * <p>
     * By default, it returns {@code Stream_To_Field} which means trying to stream the part data to the related output stream(if not null)
     * </p>
     * <p>
     * If user wishes to perform different io op over part input stream, so {@code Pass_Stream} should be returned which inform the filler to pass the part input stream to the POJO ({@code part_stream} method)
     * </p>
     * <p>
     * <b>Note:</b> If the POJO has 3 associated part({@code OutputStream}) parameter, so for each part, this method will be called(not once for all)
     * </p>
     * @return the part streaming mode need to be applied
     */
    default public Part_Field_Stream_Mode part_io_stream_mode() {
        return Part_Field_Stream_Mode.Stream_To_Field;
    }

    /**
     * Indicates if the filler is allowed to call {@code set_field_fill_result_err_msg} when failed fill event happened.
     * <p>
     * Filler asks is once for each fill operation, not for each field.
     * </p>
     * <p>
     * The message generated by the filler may be vary, or no any error message at all.
     * </p>
     * <p>
     * Please check {@code set_field_fill_result_err_msg()} method
     * </p>
     * @return {@code true} if POJO wishes for default error message generation
     */
    default public boolean generate_result_err_msg() {
        return false;
    }

    /**
     * Event by filler to POJO, to indicate the overall instance-level filling result.
     * This method is called by the filler, at the end of fields filling, to state the overall instance-level filling result
     * Any failure about a field setting will result the object filling result as failed too
     * For duplicated inner-types also, filler will set the {@code Ignorred_Duplicated_Type} as {@code arg_success} value
     * @param arg_result indicates the object filling overall result
     */
    default public void set_object_fill_result(Object_Fill_Result arg_result) {
    }

    /**
     * Field failed data setting event.
     * <p>
     * This method is called when a field setting result is failed. by "fail" it means it violets the POJO required data/state, for example null data for a non-null field, or invalid number format for a int field.
     * </p>
     * <p>
     * This method is called before {@code set_field_fill_result_err_msg()} method, if parser default err message is desired
     * </p>
     * <p>
     * <b>Note:</b> For a <u>success</u> field set(assuming correct/expected data, and or null for a nullable field), this method <u>will not</u> be called.
     * </p>
     * @param arg_param_name the parameter name from http data
     * @param arg_idx index of parameter data
     * @param arg_result the reason about the fail (always a failed one, never a success result)
     */
    default public void set_field_fill_result(String arg_param_name, int arg_idx, Field_Fill_Result arg_result) {
    }

    /**
     * Field failed data setting generated error message.
     * <p>
     * This method is called after {@code set_field_fill_result()} method, if POJO responded {@code true} by {@code generate_result_err_msg()} method
     * </p>
     * <p>
     * Default parser({@link Generic_Object_Filler}) produces the error messages as following(excluding the double-quotes):
     * </p>
     * <ul>
     * <li>When data is missed: "Missed(empty) data"</li>
     * <li>When data is out of range: "Out of range value(min: min_val , max: max_val )"</li>
     * <li>When data decode(parse) failed: "Bad data format"</li>
     * </ul>
     * @param arg_param_name The parameter name from http data
     * @param arg_idx index of parameter data
     * @param arg_err_mes human friendly error message(s) that explains the reason of failure(excluding the field and parameter info)
     */
    default public void set_field_fill_result_err_msg(String arg_param_name, int arg_idx, String arg_err_mes[]) {
    }

    /**
     * Returns POJO type descriptor.
     * <p>
     * This method is called, if the POJO returns {@code Type_Manipulator} by @{code fill_mode} method.
     * </p>
     * <p>
     * The implemented {@code Fillable_Object_Manipulator} should provide the appreciated POJO field signature
     * </p>
     * <p>
     * Filler may(by default filler) or may not check the provided POJO signature, to avoid further exceptions
     * </p>
     * <p>
     * A POJO would introduce its signature using @{code Type_Manipulator} mode, but asks the filler for reflection(auto mode)
     * </p>
     * <p>
     * By default it returns a {@code null} value, as the default value for {@code fill_mode} is set to {@code Reflection_Type_Fields}
     * </p>
     * @return a {@code null} value if parsing using reflection is desired, or a non-null {@code Fillable_Object_Manipulator} instance that explains about the POJO type
     */
    default public Fillable_Object_Manipulator get_type_descriptor() {
        return null;
    }

    /**
     * This method is called when a stream(file-upload/part) data need to be happened.
     * <p>
     * For any data file/part streaming, filler surely calls this method to inform the POJO, an upcoming file upload is on the way, so POJO could prepare some business before that
     * </p>
     * <p>
     * A POJO could have a {@code OutputStream} with value {@code null} to just inform filler/parser a file upload is required, and when file is present, parser calss this method before reald io op. user now be able to initialize the stream to a real non-null object.
     * </p>
     * <p>
     * This method is called before {@code part_stream} method
     * </p>
     * @param arg_param_name the name of the http parameter name
     * @param arg_param_idx index of the parameter
     * @param arg_part_filename file/part name of the form data, null if not available
     * @param arg_part_size size of the file upload
     * @param arg_part_mime mime type of the file if possible
     * @return {@code true} if filler need to proceed to the next streaming op, or {@code false} if the file stream should be skipped
     */
    default public boolean prepare_for_part(String arg_param_name, int arg_param_idx, String arg_part_filename, long arg_part_size, String arg_part_mime) {
        return true;
    }
    
    /**
     * This method is called after a success {@code Stream_To_Field} part stream mode.
     * <p>
     * NOTE: If the stream mode was asked as {@code Pass_Stream} by {@code part_io_stream_mode()} method, then this method will not be called by the filler.
     * </p>
     * @param arg_param_name name of the http parameter
     * @param arg_param_idx index of the http parameter
     * @param arg_success_op {@code true} if streaming has done successfully, {@code false} otherwise(e.g. io related exception, etc...)
     * @since 0.1.11
     */
    default public void part_streaming_done(String arg_param_name,int arg_param_idx,boolean arg_success_op){
    }

    /**
     * Processes the given input stream, related to a part/file-upload of related http request.
     * <p>
     * This method is called by filler, after POJO returned {@code true} on {@code prepare_for_part} method, and wished to do the io process by its own, by returning {@code Pass_Stream} by {@code part_io_stream_mode} method
     * </p>
     * <p>
     * Any exception should be handled, otherwise the rest of the fill op may be failed.
     * </p>
     * @param arg_param_name name of the http parameter (form-data)
     * @param arg_idx index of the parameter
     * @param arg_part_stream including the data related to file of http form data(probably buffered)
     */
    default public void part_stream(String arg_param_name, int arg_idx, InputStream arg_part_stream) {
    }

}
